version: 2.1
jobs:
  build:
    machine: true
    steps:
      # fix for local builds https://github.com/CircleCI-Public/circleci-cli/issues/330
      - run:
          name: Local build handling
          command: |
            if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
              if [ -d /workdir ]; then
                ln -s /workdir /tmp/_circleci_local_build_repo
              else
                echo "Run this local build using: circleci build -v \$(pwd):/workdir"
                exit 1
              fi
            fi
      - checkout
      - run:
          no_output_timeout: 24h
          command:  |
            docker version
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
            bash ~/miniconda.sh -b -p $HOME/miniconda

            # mkdir -p ~/Programs
            # export PATH="$PATH:$HOME/miniconda/bin:$HOME/Programs"
            # wget -P ~/Programs http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/2.10.5/sratoolkit.2.10.5-ubuntu64.tar.gz
            # tar zxvf sratoolkit.2.10.5-ubuntu64.tar.gz
            
            export PATH="$PATH:$HOME/miniconda/bin"
            # conda install -c bioconda -c anaconda -y sra-tools==2.10.1
            conda create -y --name sra-tools -c bioconda -c conda-forge python3 sra-tools==2.10.1
            conda activate sra-tools
            # fasterq-dump -e 8 ERR3240275 -p
            # $HOME/miniconda/bin/pip install virtualenv
            # $HOME/miniconda/bin/virtualenv -p python3 venv
            # source venv/bin/activate
            pip install cwlref-runner
            cwltool --version
            cd test
            bash test.sh
        
